package me.smorenburg.jira.db.models.base;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "SKILL".
 */
@Entity
public class Skill extends me.smorenburg.jira.db.core.DbBaseModel  {

    @Id(autoincrement = true)
    @Unique
    private Long id;
    private String tittle;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated(hash = 1993658816)
    public Skill() {
    }

    public Skill(Long id) {
        this.id = id;
    }

    @Generated(hash = 1706828541)
    public Skill(Long id, String tittle) {
        this.id = id;
        this.tittle = tittle;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTittle() {
        return tittle;
    }

    public void setTittle(String tittle) {
        this.tittle = tittle;
    }

    // KEEP METHODS - put your custom methods here

    @Override
    public String toString() {
        return tittle;
    }

    // KEEP METHODS END

}
